### ISSUE TITLE
SearchViewModel 및 Interactor 생성

### ISSUE THREAD

**Issue by JiSeobKim** [JiSeobKim/GitHubSearch#3]
# Description
- SearchVC에서 사용될 ViewModel 생성
- SearchViewModel 비즈니스 로직용 Interactor 생성

# TODO
- [x] ViewModel 생성
  - [x] Input, Output을 정의한 Protocol 생성
  - [x] TestCase 작성
  - [x] 운영 코드 구현
- [x]  Interactor 생성
  - [x] TestCase 작성
  - [x] 운영 코드 구현
